<project xmlns="http://maven.apache.org/POM/4.0.0">
    <modelVersion>4.0.0</modelVersion>
    <groupId>zw.ac.uz.dpdms</groupId>
    <artifactId>dpdms-parent</artifactId>
    <version>1.0.0</version>
    <packaging>pom</packaging>

    <parent>
        <groupId>org.springframework.boot</groupId>
        <artifactId>spring-boot-starter-parent</artifactId>
        <version>3.2.5</version>
        <relativePath/>
    </parent>

    <properties>
        <java.version>17</java.version>
        <spring-cloud.version>2023.0.1</spring-cloud.version>
    </properties>

    <modules>
        <module>discovery-service</module>
        <module>api-gateway</module>
        <module>auth-service</module>
        <module>flood-service</module>
        <module>drought-service</module>
        <module>fire-service</module>
        <module>zoonotic-disease-service</module>
        <module>mining-accident-service</module>
        <module>report-service</module>
        <module>alert-service</module>
        <module>dashboard-service</module>
    </modules>

    <dependencyManagement>
        <dependencies>
            <dependency>
                <groupId>org.springframework.cloud</groupId>
                <artifactId>spring-cloud-dependencies</artifactId>
                <version>${spring-cloud.version}</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>
        </dependencies>
    </dependencyManagement>
</project>