server:
  port: 8086
spring:
  application:
    name: mining-accident-service
  datasource:
    url: jdbc:postgresql://localhost:5432/mining_db
    username: dpdms
    password: dpdms
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    prefer-ip-address: true
    ip-address: 127.0.0.1
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
springdoc:
  swagger-ui:
    path: /swagger-ui.html